apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: base-notebook
      labels:
        app.openshift.io/runtime: python
    spec:
      source:
        git:
          ref: main
          uri: "https://github.com/myanalyticalengine/jupyter-stacks"
        contextDir: base-notebook
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: base-notebook:1.0.0
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange

  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: base-notebook
      labels:
        app.openshift.io/runtime: python
      annotations:
        description: base-notebook builder image
