apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: base-jupyter-lab
      labels:
        app.openshift.io/runtime: python
    spec:
      source:
        git:
          ref: develop
          uri: "https://github.com/myanalyticalengine/jupyter-stacks"
        contextDir: base-notebook
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          env:
            - name: JUPYTER_CMD
              value: lab
      output:
        to:
          kind: ImageStreamTag
          name: base-jupyter-lab:1.0.0
          namespace: openshift
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
